# Generated by Django 2.2.2 on 2019-06-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_Contracts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='customer_metadata',
            field=models.TextField(blank=True, null=True, verbose_name='Customer Metadata'),
        ),
    ]
