# Generated by Django 2.2.2 on 2019-06-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20190628_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='interest_rate',
            field=models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Monthly Interest Rate'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='submission_date',
            field=models.DateField(auto_now_add=True, verbose_name='Submission Date'),
        ),
    ]
