# Generated by Django 2.2.2 on 2019-06-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_Amountdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Amount Due'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submission Date'),
        ),
    ]
